### ISSUE TITLE
Labels with spaces break startup script

### ISSUE THREAD

**Issue by adenix** [hazendaz/makeself-maven-plugin#1]
Desired configuration:

```
<plugin>
  <groupId>com.githuhazendaz.maven</groupId>
  <artifactId>makeself-maven-plugin</artifactId>
  <version>1.0.0.beta3</version>
  <configuration>
    <archiveDir>${project.build.finalName}</archiveDir>
    <fileName>${project.build.finalName}.bin</fileName>
    <label>${project.name} ${project.version}</label>
    <startupScript>./install.sh</startupScript>
  </configuration>
  <executions>
    <execution>
      <id>makeself</id>
      <goals>
        <goal>makeself</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

Unfortunately this causes the follow error on run:

```
$ ./mobile-registration-0.0.1.bin  
./mobile-registration-0.0.1.bin: line 16: 0.0.1 ./install.sh: No such file or directory
Verifying archive integrity...  100%   All good.
Uncompressing   100%  
```

It tries to run `0.0.1 ./install.sh` instead of `./install.sh`.

Changing label to the following allows everything to work, but its a undesired change:

```
<label>${project.version}</label>
```

**Comment by hazendaz** [comment]
Are you sure you used beta 3?  This was fixed in beta 2.  I'll test it again this week.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by adenix** [comment]
Yeah, this segment was copied straight from my pom.xml.

macOS 10.13.1

**Comment by hazendaz** [comment]
Sorry haven't gotten to this entirely yet.  It works fine in windows and bash using it with spaces.

**Comment by hazendaz** [comment]
@adenix I was able to replicate issue with linux.  I've made some changes that I think will solve it.  If possible can you build from master and try it out to see if it fixes your issue?  If so, I'll release it in next couple of days.

**Comment by hazendaz** [comment]
@adenix This has now been confirmed fixed on linux builds.  Can you confirm macOS works on latest release?

**Comment by hazendaz** [comment]
Closing issue as this has been properly fixed and configured on windows and *nix systems so mac should be covered.  If issues persists, please open new ticket.
