### ISSUE TITLE
Breaking change in version 1.5.0

### ISSUE THREAD

**Issue by laymain** [hazendaz/makeself-maven-plugin#111]
Hi,

There is a major breaking change introduced in version 1.5.0, some validations on StartupScript have been added
to ensure that is starts with `./`.

https://github.com/hazendaz/makeself-maven-plugin/commit/3e9f7e6052e5b2621ca44804c595e7cc985761f1#diff-b6db0f63da58c2341b45523a8fa2c3615787c30e0f622022c2994ad5294a289cR496-R507

On our side, we have defined our startup script as `bash`, could you explain the motivation of this breaking change?
How could we continue using a system binary as a startup script?

Best regards.

**Comment by hazendaz** [comment]
Can you be more specific?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Julien Opoix ***@***.***>
Sent: Wednesday, November 9, 2022 11:51:16 AM
To: hazendaz/makeself-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hazendaz/makeself-maven-plugin] Breaking change in version 1.5.0 (Issue #111)


Hi,

There is a major breaking change introduced in version 1.5.0, some validations on StartupScript has been added.

makeself-maven-plugin-1.4.2...makeself-maven-plugin-1.5.0#diff-b6db0f63da58c2341b45523a8fa2c3615787c30e0f622022c2994ad5294a289cR496-R511<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhazendaz%2Fmakeself-maven-plugin%2Fcompare%2Fmakeself-maven-plugin-1.4.2...makeself-maven-plugin-1.5.0%23diff-b6db0f63da58c2341b45523a8fa2c3615787c30e0f622022c2994ad5294a289cR496-R511&data=05%7C01%7C%7C7b64e8454c1e43b135c408dac2729ec3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638036094789635825%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sUoWVoUQYmUnmd%2BIrFXzsKnJE6UtUjqtU0nqeHsPtfE%3D&reserved=0>

On our side, we have defined our startup script as bash, could you explain the motivation of this breaking change?
How could we continue using a system binary as a startup script?

Best regards.

**Comment by hazendaz** [comment]
I presume you added bash and series of args to directly call with notemp set to bypass the startup script itself which has always been documented as required with this plugin and a little looser with makeself? That is assuming that use case and not bash only calling to another script file.  If so specific support for that use case could be added as that isn't a startup script file but rather a direct script execution.  Now if you just have bash calling a script that isn't necessary as ./foo as documented throughout will properly execute.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by laymain** [comment]
Sorry if it was not clear enough.
Prior to version 1.5.0 I was able to call a binary outside the installer:
```xml
  <plugin>
      <groupId>com.github.hazendaz.maven</groupId>
      <artifactId>makeself-maven-plugin</artifactId>
      <version>1.4.2</version>
      <configuration>
          <archiveDir>dist</archiveDir>
          <fileName>${project.artifactId}-installer-${project.version}.sh</fileName>
          <label>${project.artifactId} ${project.version} installer</label>
          <startupScript>java</startupScript>
          <scriptArgs>-jar ${project.artifactId}.jar</scriptArgs>
      </configuration>
      <executions>
          <execution>
              <phase>package</phase>
              <id>makeself</id>
              <goals>
                  <goal>makeself</goal>
              </goals>
          </execution>
      </executions>
  </plugin>
```

Actually we rely on this behaviour and not able to update the plugin, could we at least have a option to bypass these validations?

**Comment by hazendaz** [comment]
@laymain Thank you!  That was very useful.  I've added a flag called 'inlineScript' which is defaulted false.  If you set that to 'true', it will now skip that verification.  It will however verify that scriptArgs were passed.  This is on master now in case you are able to test it.  Please have a look at [this](https://github.com/hazendaz/makeself-maven-plugin/commit/eef1f969cf5fe29ce1008c94495648775a9f6dcc).

Note: Makeself most likely had reworked code around this point at some point in time or at least extended part of it.  One feature not supported here currently is the notemp and not requiring startupScript at all.  That might be a useful thing but have not added it at this point.  Just noting it as the javadoc is mostly a direct port from makeself and that seemed newer.

**Comment by hazendaz** [comment]
@laymain If this works for you, I can get a release out this weekend.

**Comment by laymain** [comment]
Thank you for your reactivity!
I'll will test it tomorrow (GMT+1 timezone here) and will let you know.

**Comment by laymain** [comment]
Works like a charm 👍

**Comment by hazendaz** [comment]
Thanks, will get the release out today.

**Comment by hazendaz** [comment]
closing as resolved.
