### ISSUE TITLE
No such file or directory (error status 1) with <fileName> on Windows

### ISSUE THREAD

**Issue by frereit** [hazendaz/makeself-maven-plugin#16]
I get the following output when trying to package on windows:

```
[INFO] About to compress 185 KB of data...
[INFO] Adding files to archive named "C:\Users\FrReiter\Desktop\installer\target/installer.sh"...
[INFO] FIND: Parameterformat falsch
[INFO] tar.exe: no files or directories specified
[INFO] ERROR: failed to create temporary archive: /tmp/mkself4348.tar
[INFO]
[ERROR] makeself failed with error status: 1
[INFO] bash: C:\Users\FrReiter\Desktop\installer\target/installer.sh: No such file or directory
[INFO]
[ERROR] makeself failed with error status: 127
```

I believe the problem is that it is trying to write it's temp archive to /tmp/, which is an invalid path on windows, which leads to more errors of not finding certain files. Any fix for this?

edit: forgot to supply my pom.xml. Here is the relevant part:
```xml
<plugin>
    <groupId>com.github.hazendaz.maven</groupId>
    <artifactId>makeself-maven-plugin</artifactId>
    <version>1.1.5</version>
    <configuration>
        <archiveDir>getdown-stub/</archiveDir>
        <fileName>installer.sh</fileName>
        <label>Installer</label>
        <startupScript>java -jar getdown.jar .</startupScript>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <id>makeself</id>
            <goals>
                <goal>makeself</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by hazendaz** [comment]
I believe it cannot find the file you have named installer.sh.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by frereit** [comment]
Maybe I am interpreting this wrong, but the fileName tag should be the equivalent of the file_name argument in makeself cli. This is the OUTPUT where the sh script goes. This is confirmed when running `makeself getdown-stub installer.sh Installer "echo Test"` manually, as it compiles without a problem. From the [makeself readme:](https://github.com/megastep/makeself) `file_name is the name of the archive to be created`.

**Comment by hazendaz** [comment]
Ok I think I see now.  Try removing your / in the archive directory name and move the startup script into a script.sh file that runs the java line you want.  I think that should then clear the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by frereit** [comment]
Thank you very much, I will try this the next time I get a chance and will reopen the issue if it doesn't work.

**Comment by frereit** [comment]
Hello. Sorry for reopening this after a week, but I didn't have time to check the solution before now. Sadly, it still won't work. The path it cannot find is `C:\Users\FrReiter\Desktop\installer\target/installer.sh`. Maybe this is a problem with the inconsistency between normal slash and backslash? 
The commandline output has not changed, but I changed my maven config to this:
```xml
<plugin>
    <groupId>com.github.hazendaz.maven</groupId>
    <artifactId>makeself-maven-plugin</artifactId>
    <version>1.1.5</version>
    <configuration>
        <archiveDir>getdown-stub</archiveDir>
        <fileName>installer.sh</fileName>
        <label>Installer</label>
        <startupScript>./run.sh</startupScript>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <id>makeself</id>
            <goals>
                <goal>makeself</goal>
            </goals>
        </execution>
    </executions>
</plugin>```

**Comment by hazendaz** [comment]
@frereit Please remove buildTarget and phase parameters.  Other than that, can you upload a sample?  This library is pretty heavily used so there must be something else going on in your setup.

The setup in general other than the extra paramater which is a maven default isn't needed.  I'm doubtful that is even something documented in the plugin.  In general the default setup is the one most often used.  The archive directory has to be a directory created in your target folder which receives the label as noted.  So in your case `getdown-stub` has to be the folder for the archive content.  Then the startup script must also be in that folder.  The resulting script name is your installer.sh.  The complaint it has is that the folder it is stuggested to archive doesn't exist.  Please also remove the 'phase' from the executation.  This runs in verification by default. Generally you are running other items that assembly together your distro package.  Those run in the package phase most frequently and you need to ensure this then runs last.  Thus it's default verification step is used to achieve that.

Outside of that, if you can upload a small demo of the issue to githubt that might allow me to further help you triage the issue.

**Comment by frereit** [comment]
Sorry, my configuration was correct, this is a bug in the latest version of makeself (the prerelease on GitHub, everything works in 2.4.0). 
Pasting my edit from above for convenience.
Sorry for all the confusion. This worked for me in makeself, because I was using the latest release from the makeself GitHub, but when I try to execute bash makeself.sh getdown-stub installer.sh Installer ./run.sh manually with a clone of the latest version on github, I get the same error as per maven. Closing this here and reopening in the makeself github, sorry again.

**Comment by hazendaz** [comment]
@frereit Thanks for extra insight there.  I haven't looked over at makeself in a while so possibly it's been fixed and/or I'll await the changes...if you do get a fix over there, if you don't mind please open a request here for me to update.
