### ISSUE TITLE
script args not set as expected.

### ISSUE THREAD

**Issue by chaitanya118** [hazendaz/makeself-maven-plugin#3]
Hi,
I'm trying to set the script args in maven using -

```
<plugin>
    <groupId>com.github.hazendaz.maven</groupId>
    <artifactId>makeself-maven-plugin</artifactId>
    <version>1.0.0.beta6</version>
    <configuration>
        <archiveDir>distro</archiveDir>
        <fileName>${product.name}-${indra.version.product}-${indra.version.build}.run</fileName>
        <label>Indra Installation</label>
        <startupScript>./install.sh -version=${indra.version.product} -build=${indra.version.build}</startupScript>
    </configuration>
    <executions>
        <execution>
            <id>makeself</id>
            <goals>
                <goal>makeself</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

This mvn debug output
[DEBUG] ### [bash, C:\development\gitlab\indra\target\makeself-tmp\makeself.sh, C:\development\gitlab\indra\target/distro, C:\development\gitlab\indra\target/indra-0.8.0-20180308124520.run, Indra Installation, ./install.sh -version=0.8.0 -build=20180304121932]

In this case script args are not set properly.
The run file content - 
label="Indra Installation"
script="./install.sh -version=0.8.0 -build=20180304121932"
scriptargs=""
licensetxt=""
helpheader=''
targetdir="distro"

due to this the script does not start.

Am I doing something wrong or is it a bug??

**Comment by chaitanya118** [comment]
I think its because of the ProcessBuilder and how it treats spaces.
[https://stackoverflow.com/questions/15979476/processbuilder-not-behaving-properly-with-multiple-arguments/15979826]

**Comment by hazendaz** [comment]
The usage is to call a script, not call and pass Parameters.  Parameters if supported by makeself are sent in a separated element.  Please review make self then check optional setup in the maven plugin.  There are numerous options.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chaitanya118** [comment]
makeself supports script arguments.

> makeself.sh [args] archive_dir file_name label startup_script [script_args]
The maven plugin has support for makeself args, but no way to pass the script args.

**Comment by hazendaz** [comment]
I see.  I'll get this fixed.  Thanks for reporting it.

I'm probably going to use optional tag for clarity as other similar args are setup know.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Closing ticket as issue addressed.

**Comment by hazendaz** [comment]
You're very welcome

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
